### ISSUE TITLE
The Response content must be a string or object implementing __toString(), "object" given. 

### ISSUE THREAD

**Issue by JafirQuiroz** [spatie/analytics-reports#12]
Hello, im working with a project in laravel 4.2 and y need to make more specific querys to analytics, but this error appears, i hope you can help me this is my code:

$fecha = Carbon::now();
		 $startDate = $fecha->subWeek();
		 $endDate = $fecha;
$visitas = AnalyticsReports::performQuery($startDate,$endDate,'ga:sessions,ga:pageviews',$others = array());

**Comment by freekmurze** [comment]
I ran this code and the package could fetch results without any problems. Could you verify if the other methods of package are working? If not, verify if you've installed the package correctly.

**Comment by JafirQuiroz** [comment]
All the other methods are working correctly, except perfomQuery, is the only method that throw that error

**Comment by freekmurze** [comment]
Strange... Are you sure that the error occurs on the line with the `performQuery`-function?

**Comment by JafirQuiroz** [comment]
its strange, but after reading in forums, and debug my code i find out that the error was in the view(still not knowing what cause that error) and not in the library, because i dd() the variable and the library return the query perfectly so, ill be still searching, thank you for answer all my questions
