### ISSUE TITLE
Parse error: syntax error, unexpected '['

### ISSUE THREAD

**Issue by gaurav1992** [spatie/analytics-reports#8]
I have PHP Version 5.6.3 and i am getting same problem Parse error: syntax error, unexpected '[' .

Please suggest me what i have to do with it .

I am attaching a screen shot what my terminal says .Please do have a look .

Much appreciated 
![screen shot 2015-03-18 at 8 07 00 pm](https://cloud.githubusercontent.com/assets/4508926/6711017/7e8ca032-cdaa-11e4-8a65-6c17c066f3f5.png)

**Comment by freekmurze** [comment]
The error message indicates that the error is not caused by this package, but somewhere in the Laravel framework. 

It is highly unlikely that there is an error in that file, so I assume that there is something wrong at your end. Are you sure you are running the right PHP version?

**Comment by gaurav1992** [comment]
Yes i am using the same version i have mention above .

**Comment by freekmurze** [comment]
As mentioned before, it seems that your error is unrelated to this package. Try if you get a standard Laravel 5 working before installing this package.

**Comment by gaurav1992** [comment]
Sorry i didn't get you @freekmurze
